services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      HUGGINGFACE_API_KEY: ${HUGGINGFACE_API_KEY}
      HUGGINGFACE_IMAGE_MODEL: ${HUGGINGFACE_IMAGE_MODEL}
      HUGGINGFACE_AUDIO_MODEL: ${HUGGINGFACE_AUDIO_MODEL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    # env_file:
    #   - .env

